-- Create regions table
CREATE TABLE public.regions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

-- Create comunas table
CREATE TABLE public.comunas (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    region_id INT REFERENCES public.regions(id) ON DELETE CASCADE
);

-- Create profiles table
CREATE TYPE public.user_role AS ENUM ('admin', 'manager', 'rep');

CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    full_name TEXT,
    role public.user_role DEFAULT 'rep' NOT NULL
);

-- Create clients table
CREATE TABLE public.clients (
    rut TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE,
    phone TEXT,
    address TEXT,
    comuna_id INT REFERENCES public.comunas(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL
);

-- Create sales table
CREATE TABLE public.sales (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    amount NUMERIC NOT NULL,
    sale_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    client_rut TEXT REFERENCES public.clients(rut) ON DELETE CASCADE,
    rep_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    notes TEXT
);

-- Seed geography data
INSERT INTO public.regions (name) VALUES
('Región Metropolitana de Santiago'),
('Región de Valparaíso'),
('Región del Biobío'),
('Región de Antofagasta'),
('Región de la Araucanía')
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.comunas (name, region_id) VALUES
('Santiago', (SELECT id FROM public.regions WHERE name = 'Región Metropolitana de Santiago')),
('Providencia', (SELECT id FROM public.regions WHERE name = 'Región Metropolitana de Santiago')),
('Valparaíso', (SELECT id FROM public.regions WHERE name = 'Región de Valparaíso')),
('Viña del Mar', (SELECT id FROM public.regions WHERE name = 'Región de Valparaíso')),
('Concepción', (SELECT id FROM public.regions WHERE name = 'Región del Biobío')),
('Talcahuano', (SELECT id FROM public.regions WHERE name = 'Región del Biobío')),
('Antofagasta', (SELECT id FROM public.regions WHERE name = 'Región de Antofagasta')),
('Temuco', (SELECT id FROM public.regions WHERE name = 'Región de la Araucanía'))
ON CONFLICT (name) DO NOTHING;

-- Create client_status view
CREATE OR REPLACE VIEW public.client_status SECURITY INVOKER AS
SELECT
    c.rut,
    c.name AS client_name,
    c.email,
    c.phone,
    c.address,
    co.name AS comuna_name,
    r.name AS region_name,
    c.created_at,
    (SELECT MAX(s.sale_date) FROM public.sales s WHERE s.client_rut = c.rut) AS last_sale_date,
    CASE
        WHEN (SELECT MAX(s.sale_date) FROM public.sales s WHERE s.client_rut = c.rut) IS NULL THEN 'Red' -- No sales yet
        ELSE
            EXTRACT(DAY FROM (CURRENT_TIMESTAMP - (SELECT MAX(s.sale_date) FROM public.sales s WHERE s.client_rut = c.rut)))
    END AS days_since_last_sale_numerical,
    CASE
        WHEN (SELECT MAX(s.sale_date) FROM public.sales s WHERE s.client_rut = c.rut) IS NULL THEN 'Red'
        WHEN CURRENT_TIMESTAMP - (SELECT MAX(s.sale_date) FROM public.sales s WHERE s.client_rut = c.rut) <= INTERVAL '30 days' THEN 'Green'
        WHEN CURRENT_TIMESTAMP - (SELECT MAX(s.sale_date) FROM public.sales s WHERE s.client_rut = c.rut) <= INTERVAL '60 days' THEN 'Yellow'
        ELSE 'Red'
    END AS status_color
FROM
    public.clients c
LEFT JOIN
    public.comunas co ON c.comuna_id = co.id
LEFT JOIN
    public.regions r ON co.region_id = r.id;